version: '3.7'

services:
  fastapi-sqlalchemy:
    container_name: fastapi-sqlalchemy
    build: .
    image: fastapi-sqlalchemy:latest
    restart: always
    env_file:
      - .env
    network_mode: host
    ports:
      - 8000:8000

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    network_mode: host
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/table.sql:/docker-entrypoint-initdb.d/table.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_data
